### PR TITLE
Don't expose libzkgroup's headers as part of the Cocoapod

### PR DESCRIPTION
**Pull request by jrose-signal**

### CODE REVIEW

**Comment by jrose-signal** [comment]
@Imperiopolis-Signal too, though she's not popping up as a reviewer.

**Comment by Imperiopolis-Signal** [comment]
Did you test this? I'm surprised we'd be able to compile zkgroup-swift without those headers.

**Comment by jrose-signal** [comment]
zkgroup-swift uses a custom include path to find them; it's clients of zkgroup-swift that don't need them as part of the framework. (Technically that custom include path will get propagated to Swift clients for, um, not-great reasons.)

**Comment by Imperiopolis-Signal** [comment]
As long as you've tested it and it still compiles in Signal-iOS from clean, that's fine. (point Signal-iOS at your branch in it's podfile, do a `bundle exec pod update ZKGroup`, etc.)

I'm just concerned because it still seems to me like it shouldn't work, though, so confirmation on that would be ideal. The way cocoapods works is that all the things needed to compile are pulled in as spec'd by the podspec. Any references, etc. in the local project aren't present. So by excluding the header, I would assume no amount of custom include paths would allow us to access it – it just wont exist.

**Comment by jrose-signal** [comment]
Oops, you are correct. I didn't think about the fact that a development pod would be treated differently. Updated version incoming.

**Review by Imperiopolis-Signal — APPROVED** [review]

**Comment by jrose-signal** [comment]
This isn't urgent enough to cut a new tag, of course, but it'll be nice to have in the next one.

**Pull request merged**
